spring:
  application:
    # 服务名
    name: service-provider

  cloud:
    nacos:
      discovery:
        # 服务注册中心
        server-addr: 192.168.6.162:8848

server:
  port: 8070

# 端点健康检查
management:
  endpoints:
    web:
      exposure:
        include: "*"